name: MoveFreq
author: vemacs
version: ${project.version}
main: es.nkmem.da.movefreq.MoveFreqPlugin
depend: [ProtocolLib]
commands:
  movefreq:
    aliases: [movefrequency]
    permission: movefreq.command