name: MoveFreq
author: vemacs
version: ${project.version}-${git.branch}-${git.commit.id.abbrev}
main: es.nkmem.da.movefreq.MoveFreqPlugin
depend: [ProtocolLib]
commands:
  movefreq:
    aliases: [movefrequency]
    permission: movefreq.command